name: Test

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string

jobs:
  list-test-files:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: echo "matrix=$(node ./scripts/list-test-files.js ${{ inputs.target }})" >> $GITHUB_OUTPUT

  echo-test-files:
    runs-on: ubuntu-latest
    needs:
      - list-test-files
    steps:
      - name: Echo previous outputs
        run: echo "${{ toJSON(needs.list-test-files.outputs) }}"

  test:
    name: test ${{ matrix.file }}
    needs: [list-test-files]
    runs-on: ubuntu-latest
    env:
       TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
       TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

    strategy:
      matrix:
        file: ${{fromJSON(needs.list-test-files.outputs.matrix)}}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: node_modules-${{ hashFiles('yarn.lock') }}

      - name: Install dependencies
        run: yarn install --immutable

      - name: Test ${{ matrix.file }}
        run: yarn test --filter=${{ inputs.target }}
        env:
          FILE: ${{ matrix.file }}

  test-success:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - run: echo "Success"